# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TZImagePickerDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TZImagePickerDemo

  pod 'TZImagePickerController'
  pod 'SDWebImage'
  
  target 'TZImagePickerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TZImagePickerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
